language: node_js
node_js:
- '4.4'
env:
- SAUCE_USERNAME=opentok
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
  - npm run build;
  - npm test;
  - if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      bash <(curl -s https://codecov.io/bash);
    fi
  - VER_DEPL=$(npm show opentok-annotation version);
  - VERSION=$(jq '.version' package.json | sed -e 's/^"//' -e 's/"$//');
deploy:
  provider: npm
  email: vsolutions@tokbox.com
  api_key:
    secure: JgU2EYey5OIHA/9g62g7ebm/6zD3jy1ZbQyG3G04kkg3B6bZCo+2PaAwGQ9mcN4yoywSXnqsVfADpHfUqfFErnYAiJf4B/+H2bVTGTKH5PUYQpE6g4v2Vl80tzoyhE/Jsi/sXcsI3RUCDomtyvMGVQ2FZB7KXPpwwgXN693bsuobg/3BZ0yAVuk9EDXtd8XvIBubGXVb5vXPdPt9gwKFrH28IDWyFuaFwa4JesWXfG8+4xFDyVqSEtKlG2TeAKiO3lvV2qeIFsHfp8s80caeUinADaJsl38KTvQbBPyfjpplN1Sypp+NIlfYFD3YXuK9Rs+/QgJrkDJDztxR6mjj77LIrC91+cX71mfX9VleneUFni2+fJLJnc7GfusmTIT3SFJ5PB6vglBAmCtY83Mu8650vZWv0x7tyR4CXXDFl+2WBT2ZixGE5eM83BJiOqPycSYUImpfxsS0cppYuU8Dwm8p1rU6uwfVtjTHTXr3EUt/14G6GwE0pyW6Na3IRPrflRe0zQgNrSp64JDdpX2vKtU6tVRdXTETONnigmtVpCVQJ3bZp9RQSg4mWlzDJfn3yyQBMPFWsaz27a+PBNOEqwx+pFm7Yzl++jngPYv4bdAsewfbPNXF2q2iumhBNI22KK40JVp6/aXt9LUS9lQ5A+yistntS7p6EHxK8w499Uk=
  on:
    branch: master
    condition: $VERSION != $VER_DEPL
after_deploy:
  - git commit -m "New build. Bump npm version." --allow-empty;
  - git tag v$VERSION;
  - git push --quiet https://$GITHUBKEY@github.com/opentok/accelerator-annotation-js v$VERSION;
notifications:
  slack:
    secure: gnKw/BvuTAKFIxVwn0CtaEli4Md7NZPb3Pz0OqadzPv69jXKe1UehR1aunif6uae71Or1LqV19ez1/6JnjLjLpjQ0Zr4qmN+hY4mDNkuIToValGmsaRBqaB10JVzbgDvH2gZfucMdazpoPhNxbixRZw89hnm2psyJbm9nx2Ys9BGzu/F0D1+wIkVhsuLWf5NHUURSgSUvUvKuJtgX7HetbADbs5tqABGoKkBVhoWEyVKEn3TCKTczIaw2xFMXbt3KTFohlUM2wg2KqmbEHAZ1cbb6dWJM6chaLeBuBIv+HAjgWEz6kL8ongo8kvz2ip/x/xcrLfJXFC2tJjTHCVpYLmKhTWoVlAVBDKrEQEfDZTpbxUUO+BEAE7Fr+6RkNYdgdOqtVXLHaFRcbRUSUV+x7TJCKboZ06suKUFjzjZsHxST2xHDk8NNLcGr8e54SJl+44bgPRXTSStlNqf5ZQxS/bThgnb79nWgRc5eBxkbRThWRgnJwzSpAoDY2qWRcb+wtN/ct8mEvKNMCS+V4LZNdZbbk+77enZEeYBFgb7JcBrXZ3/xdUbNsKDRN66n2q8/O+cLKEjLQORd+43w1WoAMa/EL8kqOKQvu22Is6E0gyH0HiTHlY2rfm4hfyofD4yH8s1KbNk+tqQPQuHVaNTBl+8fOStHKUO0zJeHD4Kj9M=
addons:
  jwt:
    secure: Z+gEkV+OzmCpa7Ea74G8A2xZeymKsx2cRBOQE79yfGG7YJg/yG+EhhSg4XbPKGksy85P7Rb+cBbs48RfRwRyb64g5nCsOPfUwWB6Jp5d2WCXCl2FXWSfIu9lozRyOjSNbtqQiErE+fMN311eNN06bjhcDyH4DsBk5C5EigTYCN2zNusBuelc10N81Lt2bqzA7KZehw3ItJuBhnnSLSVIMDUdBxyrtJ7yHrkkXWJdmFnaalCnaNq+OovMZdFYMfoXzDFq2UUcnL4khjosVDhMQlpajuB2oLbCK8VBd8buh3/faEd5WOQRv1lJvVDnkMFnHgBXrDhHjJQeh8H1ht/ikR8e3bzJXpJMCXANXsWcxBDnA6J58B21fpiCcrJxzogzqg6IDfxkScOS1zPe4U79aCwoawfrnOgrA9ivmRVM3rvYSDJB2L3gAQKnIO2VUKb0W+le454Gi8YOfEslXrgWYVi3hiJLsWMKN6JyjRJLURTa6xQ9lvcsQeq9dVZeZF3G+wGLcOwdUupvV7tWI8pdn3j3B6b95972xoppT9Czy3hfGSS6bfhYTZQqixiTjBEUUsGYSYJ/op8NPIfxvbyGy5tpe7tK7Q/Oz12GbXAGe+1r7j6MKlWlIIFE6XMKMA3oNFP6AEwmiW7cD0uA5OcKjnF1vb4Lv1yXjX4axOhFTTw=
